use crate::data::{OrderBook, Ticker};
use crate::trading::order::Position;
use rust_decimal::Decimal;

/// Signal generated by a strategy
#[derive(Debug, Clone)]
pub enum Signal {
    /// No action to take
    Hold,
    /// Open a long position
    Buy { pair: String, quantity: Decimal },
    /// Close an existing position
    Sell { pair: String },
}

/// Trait for trading strategies
pub trait Strategy: Send + Sync {
    /// Analyze market data and generate trading signals
    fn analyze(
        &mut self,
        ticker: &Ticker,
        orderbook: Option<&OrderBook>,
        position: Option<&Position>,
    ) -> Signal;

    /// Check if we should take profit on an existing position
    fn should_take_profit(&self, position: &Position, current_price: Decimal) -> bool;

    /// Check if we should cut losses on an existing position
    fn should_stop_loss(&self, position: &Position, current_price: Decimal) -> bool;

    /// Get the name of the strategy
    fn name(&self) -> &str;

    /// Reset strategy state (e.g., on reconnection)
    fn reset(&mut self);
}
